name: absensi_operator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
   sdk: ">=3.2.5 <4.0.0" 

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.3
  lottie: ^3.1.3
  page_transition: ^2.1.0
  flutter_svg: ^2.0.10+1
  dotted_line: ^3.2.3
  intl: ^0.19.0
  camera: ^0.11.0+1
  logger: ^2.4.0
  url_launcher: ^6.3.0
  smooth_page_indicator: ^1.2.0+3
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  screen_brightness: ^2.0.0+2
  device_info_plus: ^11.1.1
  shared_preferences: ^2.3.3
  awesome_notifications: ^0.10.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  android_intent_plus: ^5.2.0
  workmanager: ^0.5.2
  shimmer: ^3.0.0
  flutter_background_service: ^5.0.10
  flutter_foreground_task: ^8.17.0
  
dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueBold.otf
        - asset: assets/fonts/HelveticaNeueLight.otf
        - asset: assets/fonts/HelveticaNeueMedium.otf
        - asset: assets/fonts/HelveticaNeueThin.otf
        
  uses-material-design: true
